// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Req struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

type UserID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CarID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarID) Reset()         { *m = CarID{} }
func (m *CarID) String() string { return proto.CompactTextString(m) }
func (*CarID) ProtoMessage()    {}
func (*CarID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *CarID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarID.Unmarshal(m, b)
}
func (m *CarID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarID.Marshal(b, m, deterministic)
}
func (m *CarID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarID.Merge(m, src)
}
func (m *CarID) XXX_Size() int {
	return xxx_messageInfo_CarID.Size(m)
}
func (m *CarID) XXX_DiscardUnknown() {
	xxx_messageInfo_CarID.DiscardUnknown(m)
}

var xxx_messageInfo_CarID proto.InternalMessageInfo

func (m *CarID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EngineID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EngineID) Reset()         { *m = EngineID{} }
func (m *EngineID) String() string { return proto.CompactTextString(m) }
func (*EngineID) ProtoMessage()    {}
func (*EngineID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *EngineID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EngineID.Unmarshal(m, b)
}
func (m *EngineID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EngineID.Marshal(b, m, deterministic)
}
func (m *EngineID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EngineID.Merge(m, src)
}
func (m *EngineID) XXX_Size() int {
	return xxx_messageInfo_EngineID.Size(m)
}
func (m *EngineID) XXX_DiscardUnknown() {
	xxx_messageInfo_EngineID.DiscardUnknown(m)
}

var xxx_messageInfo_EngineID proto.InternalMessageInfo

func (m *EngineID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CarsIDs struct {
	CarsIDs              []int32  `protobuf:"varint,1,rep,packed,name=carsIDs,proto3" json:"carsIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarsIDs) Reset()         { *m = CarsIDs{} }
func (m *CarsIDs) String() string { return proto.CompactTextString(m) }
func (*CarsIDs) ProtoMessage()    {}
func (*CarsIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *CarsIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarsIDs.Unmarshal(m, b)
}
func (m *CarsIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarsIDs.Marshal(b, m, deterministic)
}
func (m *CarsIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarsIDs.Merge(m, src)
}
func (m *CarsIDs) XXX_Size() int {
	return xxx_messageInfo_CarsIDs.Size(m)
}
func (m *CarsIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_CarsIDs.DiscardUnknown(m)
}

var xxx_messageInfo_CarsIDs proto.InternalMessageInfo

func (m *CarsIDs) GetCarsIDs() []int32 {
	if m != nil {
		return m.CarsIDs
	}
	return nil
}

type Car struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Concern              string   `protobuf:"bytes,2,opt,name=concern,proto3" json:"concern,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year                 int32    `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Used                 bool     `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	EngineID             int32    `protobuf:"varint,6,opt,name=engineID,proto3" json:"engineID,omitempty"`
	Price                int32    `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Car) GetConcern() string {
	if m != nil {
		return m.Concern
	}
	return ""
}

func (m *Car) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Car) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Car) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

func (m *Car) GetEngineID() int32 {
	if m != nil {
		return m.EngineID
	}
	return 0
}

func (m *Car) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Cars struct {
	Cars                 []*Car   `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cars) Reset()         { *m = Cars{} }
func (m *Cars) String() string { return proto.CompactTextString(m) }
func (*Cars) ProtoMessage()    {}
func (*Cars) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{6}
}

func (m *Cars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cars.Unmarshal(m, b)
}
func (m *Cars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cars.Marshal(b, m, deterministic)
}
func (m *Cars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cars.Merge(m, src)
}
func (m *Cars) XXX_Size() int {
	return xxx_messageInfo_Cars.Size(m)
}
func (m *Cars) XXX_DiscardUnknown() {
	xxx_messageInfo_Cars.DiscardUnknown(m)
}

var xxx_messageInfo_Cars proto.InternalMessageInfo

func (m *Cars) GetCars() []*Car {
	if m != nil {
		return m.Cars
	}
	return nil
}

type Engine struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Volume               float32  `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Engine) Reset()         { *m = Engine{} }
func (m *Engine) String() string { return proto.CompactTextString(m) }
func (*Engine) ProtoMessage()    {}
func (*Engine) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{7}
}

func (m *Engine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Engine.Unmarshal(m, b)
}
func (m *Engine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Engine.Marshal(b, m, deterministic)
}
func (m *Engine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Engine.Merge(m, src)
}
func (m *Engine) XXX_Size() int {
	return xxx_messageInfo_Engine.Size(m)
}
func (m *Engine) XXX_DiscardUnknown() {
	xxx_messageInfo_Engine.DiscardUnknown(m)
}

var xxx_messageInfo_Engine proto.InternalMessageInfo

func (m *Engine) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Engine) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type Engines struct {
	Engines              []*Engine `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Engines) Reset()         { *m = Engines{} }
func (m *Engines) String() string { return proto.CompactTextString(m) }
func (*Engines) ProtoMessage()    {}
func (*Engines) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{8}
}

func (m *Engines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Engines.Unmarshal(m, b)
}
func (m *Engines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Engines.Marshal(b, m, deterministic)
}
func (m *Engines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Engines.Merge(m, src)
}
func (m *Engines) XXX_Size() int {
	return xxx_messageInfo_Engines.Size(m)
}
func (m *Engines) XXX_DiscardUnknown() {
	xxx_messageInfo_Engines.DiscardUnknown(m)
}

var xxx_messageInfo_Engines proto.InternalMessageInfo

func (m *Engines) GetEngines() []*Engine {
	if m != nil {
		return m.Engines
	}
	return nil
}

type EnginesIDs struct {
	EnginesIDs           []int32  `protobuf:"varint,1,rep,packed,name=enginesIDs,proto3" json:"enginesIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnginesIDs) Reset()         { *m = EnginesIDs{} }
func (m *EnginesIDs) String() string { return proto.CompactTextString(m) }
func (*EnginesIDs) ProtoMessage()    {}
func (*EnginesIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{9}
}

func (m *EnginesIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnginesIDs.Unmarshal(m, b)
}
func (m *EnginesIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnginesIDs.Marshal(b, m, deterministic)
}
func (m *EnginesIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnginesIDs.Merge(m, src)
}
func (m *EnginesIDs) XXX_Size() int {
	return xxx_messageInfo_EnginesIDs.Size(m)
}
func (m *EnginesIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_EnginesIDs.DiscardUnknown(m)
}

var xxx_messageInfo_EnginesIDs proto.InternalMessageInfo

func (m *EnginesIDs) GetEnginesIDs() []int32 {
	if m != nil {
		return m.EnginesIDs
	}
	return nil
}

type Resp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{10}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

type UpdateEngineRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Volume               float32  `protobuf:"fixed32,2,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEngineRequest) Reset()         { *m = UpdateEngineRequest{} }
func (m *UpdateEngineRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEngineRequest) ProtoMessage()    {}
func (*UpdateEngineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{11}
}

func (m *UpdateEngineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEngineRequest.Unmarshal(m, b)
}
func (m *UpdateEngineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEngineRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEngineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEngineRequest.Merge(m, src)
}
func (m *UpdateEngineRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEngineRequest.Size(m)
}
func (m *UpdateEngineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEngineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEngineRequest proto.InternalMessageInfo

func (m *UpdateEngineRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateEngineRequest) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func init() {
	proto.RegisterType((*Req)(nil), "proto.Req")
	proto.RegisterType((*UserID)(nil), "proto.UserID")
	proto.RegisterType((*CarID)(nil), "proto.CarID")
	proto.RegisterType((*EngineID)(nil), "proto.EngineID")
	proto.RegisterType((*CarsIDs)(nil), "proto.CarsIDs")
	proto.RegisterType((*Car)(nil), "proto.Car")
	proto.RegisterType((*Cars)(nil), "proto.Cars")
	proto.RegisterType((*Engine)(nil), "proto.Engine")
	proto.RegisterType((*Engines)(nil), "proto.Engines")
	proto.RegisterType((*EnginesIDs)(nil), "proto.EnginesIDs")
	proto.RegisterType((*Resp)(nil), "proto.Resp")
	proto.RegisterType((*UpdateEngineRequest)(nil), "proto.UpdateEngineRequest")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x6d, 0xda, 0x24, 0x2d, 0xd3, 0x8f, 0x05, 0x83, 0x16, 0x2b, 0x87, 0x55, 0x65, 0x24, 0xe8,
	0x01, 0x0a, 0x5b, 0x10, 0x42, 0x42, 0x48, 0xd0, 0x04, 0x55, 0xb9, 0x1a, 0xed, 0x85, 0x5b, 0xb6,
	0x1d, 0x56, 0x91, 0xb2, 0x49, 0x6a, 0xa7, 0x2b, 0xf5, 0xd7, 0xf0, 0xc3, 0xf8, 0x2b, 0x1c, 0x50,
	0x6c, 0x27, 0xdd, 0xb4, 0x91, 0xd8, 0x53, 0xfc, 0x66, 0xe6, 0xcd, 0xbc, 0x79, 0x8e, 0x61, 0x22,
	0x51, 0xdc, 0xc5, 0x6b, 0x94, 0xf3, 0x5c, 0x64, 0x45, 0x46, 0x1c, 0xf5, 0x61, 0x0e, 0xf4, 0x38,
	0x6e, 0x19, 0x05, 0xf7, 0x4a, 0xa2, 0x08, 0x03, 0x32, 0x81, 0x6e, 0xbc, 0xa1, 0xd6, 0xd4, 0x9a,
	0x39, 0xbc, 0x1b, 0x6f, 0xd8, 0x73, 0x70, 0xfc, 0xa8, 0x2d, 0xe1, 0xc1, 0xe0, 0x7b, 0x7a, 0x13,
	0xa7, 0xd8, 0x92, 0x7b, 0x01, 0x7d, 0x3f, 0x12, 0x32, 0x0c, 0x24, 0xa1, 0xd0, 0x5f, 0xeb, 0x23,
	0xb5, 0xa6, 0xbd, 0x99, 0xc3, 0x2b, 0xc8, 0x7e, 0x5b, 0xd0, 0xf3, 0x23, 0x71, 0x4c, 0x56, 0x8c,
	0x2c, 0x5d, 0xa3, 0x48, 0x69, 0x77, 0x6a, 0xcd, 0x1e, 0xf1, 0x0a, 0x92, 0x67, 0xe0, 0xdc, 0x66,
	0x1b, 0x4c, 0x68, 0x4f, 0xc5, 0x35, 0x20, 0x04, 0xec, 0x3d, 0x46, 0x82, 0xda, 0xaa, 0x83, 0x3a,
	0x97, 0xb1, 0x9d, 0xc4, 0x0d, 0x75, 0xa6, 0xd6, 0x6c, 0xc0, 0xd5, 0x99, 0x78, 0x30, 0x40, 0x23,
	0x98, 0xba, 0xaa, 0xb6, 0xc6, 0x65, 0xe7, 0x5c, 0xc4, 0x6b, 0xa4, 0x7d, 0x95, 0xd0, 0x80, 0xbd,
	0x04, 0xbb, 0x5c, 0x83, 0x5c, 0x80, 0x5d, 0x8a, 0x56, 0x0b, 0x0c, 0x17, 0xa0, 0x1d, 0x9c, 0xfb,
	0x91, 0xe0, 0x2a, 0xce, 0xde, 0x81, 0xab, 0xad, 0x38, 0xd9, 0xe5, 0x1c, 0xdc, 0xbb, 0x2c, 0xd9,
	0xdd, 0xa2, 0x5a, 0xa5, 0xcb, 0x0d, 0x62, 0x0b, 0xe8, 0x6b, 0x86, 0x24, 0xaf, 0xa0, 0xaf, 0x65,
	0x54, 0xfd, 0xc7, 0xa6, 0xbf, 0x2e, 0xe0, 0x55, 0x96, 0xbd, 0x06, 0x30, 0x9c, 0xd2, 0xd7, 0x0b,
	0x00, 0xac, 0x91, 0xb1, 0xf6, 0x5e, 0x84, 0xb9, 0x60, 0x73, 0x94, 0x39, 0xfb, 0x02, 0x4f, 0xaf,
	0xf2, 0x4d, 0x54, 0xa0, 0x69, 0x87, 0xdb, 0x1d, 0xca, 0xe2, 0xa1, 0x42, 0x17, 0x7f, 0xbb, 0x30,
	0xd6, 0xcc, 0x1f, 0xfa, 0xff, 0x21, 0x6f, 0x60, 0xbc, 0xc2, 0xe2, 0x5b, 0x92, 0x54, 0x0b, 0x54,
	0x7e, 0x70, 0xdc, 0x7a, 0x93, 0x86, 0x76, 0xc9, 0x3a, 0xe4, 0x23, 0x9c, 0xad, 0xb0, 0x30, 0x78,
	0xb9, 0x2f, 0xa5, 0x3f, 0x69, 0x16, 0x85, 0x81, 0x6c, 0xe1, 0x7d, 0x80, 0xc7, 0x35, 0x6f, 0xb9,
	0xd7, 0xbf, 0xe0, 0x59, 0xa3, 0x2a, 0x0c, 0xbc, 0xa6, 0x55, 0xac, 0x43, 0xe6, 0x30, 0xf2, 0x05,
	0xd6, 0xdb, 0x92, 0x66, 0xc1, 0x69, 0xfd, 0xa5, 0x5a, 0xa6, 0x9a, 0xf2, 0xa0, 0x11, 0x9f, 0x61,
	0x74, 0xdf, 0x50, 0xe2, 0x99, 0x82, 0x16, 0x97, 0x5b, 0xf5, 0x05, 0x98, 0x60, 0x4d, 0x3e, 0x19,
	0x37, 0xac, 0xcd, 0x94, 0x39, 0xeb, 0x2c, 0xbe, 0xc2, 0xb0, 0x7c, 0x97, 0x95, 0xf7, 0x97, 0x30,
	0x59, 0x61, 0x61, 0x9e, 0x96, 0xd2, 0x5b, 0x4d, 0xd0, 0xaf, 0xb7, 0xf6, 0xd1, 0x94, 0xb0, 0xce,
	0xe2, 0x8f, 0x05, 0xe0, 0x47, 0xe2, 0x70, 0x7b, 0x23, 0xd3, 0x41, 0xdf, 0xc5, 0x11, 0xa1, 0x9e,
	0x5f, 0x62, 0xa5, 0x77, 0x58, 0xfb, 0x13, 0x06, 0x64, 0x74, 0xc8, 0x86, 0x81, 0x77, 0x2c, 0x5e,
	0xdd, 0xda, 0xc1, 0x4f, 0xd9, 0xd6, 0xff, 0xf4, 0xee, 0x59, 0x87, 0x7c, 0x82, 0x73, 0xed, 0x8a,
	0x1f, 0x09, 0x3f, 0x4b, 0x7f, 0xc5, 0x37, 0x3b, 0x11, 0x15, 0x71, 0x96, 0xfe, 0xcf, 0x9f, 0xa5,
	0xfb, 0xd3, 0x9e, 0xbf, 0xcd, 0xaf, 0xaf, 0x5d, 0x15, 0x7d, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0x7c, 0x47, 0xfc, 0xe6, 0x04, 0x00, 0x00,
}
